name: CI Pipeline (Argo CD â€“ GitOps)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: something-api
  IMAGE_TAG: ${{ github.sha }}
  VALUES_FILE: temps/value.yaml

jobs:
  security:
    runs-on: [self-hosted, security]

    steps:
      - uses: actions/checkout@v4

      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          exit-code: 1
  build:
    runs-on: [self-hosted, docker]
    needs: security

    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG \
            ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          
  update-manifests:
    runs-on: [self-hosted, linux]
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITOPS_PAT }}

      - name: Update image tag in value.yaml
        run: |
          sed -i "s|imageTag:.*|imageTag: \"$IMAGE_TAG\"|g" $VALUES_FILE

      - name: Commit & Push
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@github.com"
          git add .
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
